### ISSUE TITLE
'url' is not a valid tag library

### ISSUE THREAD

**Issue by kunwarakash** [epantry/django-sql-explorer#167]
Localhost:15500/explorer/ give 'url' is not a valid tag library

**Comment by grantmcconnaughey** [comment]
Which version of django-sql-explorer are you using? I think this was fixed in version 0.8.0.

**Comment by kunwarakash** [comment]
I am django-sql-explorer version 0.8.0 only, but the issue is still there.

**Comment by grantmcconnaughey** [comment]
What version of Django are you using? What version of Python? Please copy and paste the entire traceback.

**Comment by kunwarakash** [comment]
I am using 
django 1.8.3
Python 2.7.6
sorry I don't have traceback as i have already made the changes and started working on my django sql explorer project.

**Comment by chrisclark** [comment]
I believe this has been fixed in master, but was *not* released in 0.8.0.

@kunwarakash can you give master a shot and see if the issue goes away?

Explorer is due for another release (some new features as well! pivot tables!) -- I will do my best to get to it this week, but I'm pretty busy so it might be next week, sorry!

**Comment by tobiase** [comment]
Using master resolves the error for me.

**Comment by chrisclark** [comment]
Thanks all. Closing and will do a new release soon.
